"""Validate lyrics, generate the browser data, and package the static website."""
import json
import shutil

from save_lyrics import ROOT
from validate_lyrics import validate


def build():
    validate()
    catalog = json.loads((ROOT / 'data/hopeful-feathers.json').read_text(encoding='utf-8'))
    songs = []
    for album in catalog['albums']:
        for track in album['tracks']:
            data = json.loads((ROOT / 'data' / track['lyricsFile']).read_text(encoding='utf-8'))
            songs.append({
                'id': data['id'], 'albumId': album['id'], 'albumName': album['artist'].replace('Team.', ''),
                'trackNumber': data['trackNumber'], 'title': data['title'], 'vocal': data['vocal'],
                'stanzas': data['stanzas']
            })
    payload = json.dumps(songs, ensure_ascii=False, separators=(',', ':')).replace('\u2028', '\\u2028').replace('\u2029', '\\u2029')
    (ROOT / 'songs.js').write_text('// Generated by scripts/build_site.py. Edit data/lyrics/*.json instead.\nwindow.SONGBOOK_DATA = ' + payload + ';\n', encoding='utf-8')
    destination = ROOT / 'dist'
    destination.mkdir(exist_ok=True)
    for name in ['index.html', 'styles.css', 'app.js', 'songs.js']:
        shutil.copyfile(ROOT / name, destination / name)
    (destination / '.nojekyll').write_text('', encoding='utf-8')
    print(f'Built {len(songs)} songs in dist/ (also available from root index.html)')


if __name__ == '__main__':
    build()
